### 포트폴리오 생성
### - 필수 입력값 : 영상, 썸네일, 제목, 테마, 공개범위(공개, 비공개)
### - 선택 입력값 : 웹 주소, 설명, 참여자 아이디, 깃헙 주소
POST /localhost:8080/portfolio/v1
Content-Type: application/json

{
    "title": "포트폴리오 제목",
    "description": "포트폴리오 설명",
    "theme": "WEB",
    "webUrl": "포트폴리오 웹 주소",
    "gitUrl": "포트폴리오 깃헙 주소",
    "protectType": "PUBLIC",
    "userId": [2,3],
    "videoUid": "영상 UID",
    "thumbnailUid": "썸네일 UID",
    "createdBy": 1
}

### 포트폴리오 수정
### 수정 범위 : 제목, 테마, 공개범위, 웹 주소, 설명, 참여자 아이디, 깃헙 주소
PUT /localhost:8080/portfolio/v1/1
Content-Type: application/json

{
    "title": "포트폴리오 제목",
    "description": "포트폴리오 설명",
    "theme": "WEB",
    "webUrl": "포트폴리오 웹 주소",
    "gitUrl": "포트폴리오 깃헙 주소",
    "protectType": "PUBLIC",
    "userId": [2,3],
    "updatedBy": 1
}

### 포트폴리오 삭제
DELETE /localhost:8080/portfolio/v1/1
Content-Type: application/json

{
    "createdBy": 1
}
